### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by domenor** [liamjack/Auth#4]
Hi, in localhost its works fine, but in ipage hosting show erros:
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>500 Internal Server Error</title>
</head><body>

<h1>Internal Server Error</h1>

<p>The server encountered an internal error or
misconfiguration and was unable to complete
your request.</p>

<p>Please contact the server administrator,
 cgiadmin@yourhostingaccount.com and inform them of the time the error occurred,
and anything you might have done that may have
caused the error.</p>

<p>More information about this error may be available
in the server error log.</p>

<p>Additionally, a 500 Internal Server Error
error was encountered while trying to use an ErrorDocument to handle the request.</p>

</body></html>

Un saludo desde Chile

**Comment by liamjack** [comment]
Hi. The problem is with the `.htaccess` file I think, your web host maybe doesn't have `mod_rewrite` enabled and that's why the 500 Internal Server Error pops up. Maybe try another hosting service, or if not you could try removing the need for `mod_rewrite`, but you would then have a lot of rewriting to do !

Un saludo desde Francia !
